/* eslint-disable */
/**
 * Generated by scripts/gen-contract-types.cjs — do not edit.
 * Regenerate: npm run gen:contract (or check:contract --fix).
 *
 * The data contract: every dynamic value in the kit renders from
 * window.mockData. Wire a backend by serving the same shape.
 */
declare namespace DreamBoard {
  type PosValue = "bottom" | "top";
  type StatusValue = "active" | "available" | "beta" | "cancelled" | "delivered" | "deprecated" | "disabled" | "error" | "failed" | "in stock" | "inactive" | "invited" | "low stock" | "out of stock" | "paid" | "paused" | "pending" | "processing" | "ready" | "refunded" | "revoked" | "running" | "scheduled";
  type TypeValue = "area" | "auth" | "bar" | "candlestick" | "data" | "donut" | "email" | "heatmap" | "line" | "password" | "polarArea" | "radar" | "radialBar" | "rangeBar" | "scatter" | "security" | "tel" | "text" | "treemap" | "world";
  type VariantValue = "danger" | "default" | "info" | "primary" | "success" | "warning";
  interface MockData {
    site: DreamBoard.Site;
    user: DreamBoard.User;
    nav: DreamBoard.Nav[];
    stats: DreamBoard.Stat[];
    revenueChart: DreamBoard.RevenueChart;
    ordersChart: DreamBoard.OrdersChart;
    recentOrders: DreamBoard.RecentOrder[];
    topProducts: DreamBoard.TopProduct[];
    userAgents: DreamBoard.UserAgent[];
    activity: DreamBoard.Activity[];
    notifications: DreamBoard.Notification[];
    userMenu: DreamBoard.UserMenu[];
    pages: DreamBoard.Page;
    ui: DreamBoard.Ui;
    ai: DreamBoard.Ai;
  }
  interface Site {
    name: string;
    tagline: string;
  }
  interface User {
    name: string;
    email: string;
    role: string;
    initials: string;
    photo: null;
  }
  interface Nav {
    label: string;
    icon: string;
    href?: string;
    children?: DreamBoard.NavChildren[];
  }
  interface NavChildren {
    label: string;
    href: string;
  }
  interface Stat {
    id: string;
    label: string;
    value: number;
    format: string;
    delta: string;
    deltaDir: string;
    deltaLabel: string;
    icon: string;
    spark: number[];
  }
  interface RevenueChart {
    label: string;
    series: DreamBoard.RevenueChartSeries[];
    labels: string[];
    yAxisLabel: string;
  }
  interface RevenueChartSeries {
    name: string;
    data: number[];
  }
  interface OrdersChart {
    label: string;
    labels: string[];
    data: number[];
  }
  interface RecentOrder {
    id: string;
    customer: string;
    product: string;
    date: string;
    amount: number;
    status: DreamBoard.StatusValue;
  }
  interface TopProduct {
    name: string;
    category: string;
    price: number;
    sold: number;
    stock: number;
  }
  interface UserAgent {
    name: string;
    icon: string;
    share: number;
    sessions: number;
  }
  interface Activity {
    actor: string;
    action: string;
    target: string;
    time: string;
    icon: string;
  }
  interface Notification {
    id: number;
    title: string;
    body: string;
    time: string;
    unread: boolean;
    icon: string;
  }
  interface UserMenu {
    label: string;
    href: string;
    icon: string;
  }
  interface Page {
    profile: DreamBoard.PageProfile;
    settings: DreamBoard.PageSetting;
    account: DreamBoard.PageAccount;
    billing: DreamBoard.PageBilling;
    signout: DreamBoard.PageSignout;
    analytics: DreamBoard.PageAnalytic;
    reports: DreamBoard.PageReport;
    realtime: DreamBoard.PageRealtime;
    reportNew: DreamBoard.PageReportNew;
    orders: DreamBoard.PageOrder;
    products: DreamBoard.PageProduct;
    customers: DreamBoard.PageCustomer;
    notificationsPage: DreamBoard.PageNotificationsPage;
    auditLog: DreamBoard.PageAuditLog;
    tasks: DreamBoard.PageTask;
    calendar: DreamBoard.PageCalendar;
    auth: DreamBoard.PageAuth;
    inbox: DreamBoard.PageInbox;
    files: DreamBoard.PageFile;
    invoice: DreamBoard.PageInvoice;
    pricing: DreamBoard.PagePricing;
    user: DreamBoard.PageUser;
    landing: DreamBoard.PageLanding;
    landing2: DreamBoard.PageLanding2;
    landing3: DreamBoard.PageLanding3;
    landing4: DreamBoard.PageLanding4;
    landing5: DreamBoard.PageLanding5;
    landing6: DreamBoard.PageLanding6;
    charts: DreamBoard.PageChart;
    chartsAdvanced: DreamBoard.PageChartsAdvanced;
    faq: DreamBoard.PageFaq;
    help: DreamBoard.PageHelp;
    forms: DreamBoard.PageForm;
    onboarding: DreamBoard.PageOnboarding;
    aiChat: DreamBoard.PageAiChat;
    aiAgents: DreamBoard.PageAiAgent;
    aiPrompts: DreamBoard.PageAiPrompt;
    aiModels: DreamBoard.PageAiModel;
    aiUsage: DreamBoard.PageAiUsage;
    aiKeys: DreamBoard.PageAiKey;
    aiMembers: DreamBoard.PageAiMember;
    explorer: DreamBoard.PageNotificationsPage;
  }
  interface PageProfile {
    heading: string;
    bio: string;
    location: string;
    joined: string;
    phone: string;
    website: string;
    stats: DreamBoard.PageProfileStat[];
  }
  interface PageProfileStat {
    label: string;
    value: number;
  }
  interface PageSetting {
    heading: string;
    sub: string;
    generalFields: DreamBoard.PageSettingGeneralField[];
    selects: DreamBoard.PageSettingSelect[];
    toggles: DreamBoard.PageSettingToggle[];
    danger: DreamBoard.PageSettingDanger;
  }
  interface PageSettingGeneralField {
    id: string;
    label: string;
    value: string;
    type: DreamBoard.TypeValue;
  }
  interface PageSettingSelect {
    id: string;
    label: string;
    options: string[];
    value: string;
  }
  interface PageSettingToggle {
    id: string;
    label: string;
    desc: string;
    checked: boolean;
  }
  interface PageSettingDanger {
    text: string;
    action: string;
  }
  interface PageAccount {
    heading: string;
    sub: string;
    personalFields: DreamBoard.PageAccountPersonalField[];
    bio: DreamBoard.PageAccountBio;
    photo: DreamBoard.PageAccountPhoto;
    passwordFields: DreamBoard.PageAccountPasswordField[];
    toggles: DreamBoard.PageSettingToggle[];
  }
  interface PageAccountPersonalField {
    id: string;
    label: string;
    value: string;
    type: DreamBoard.TypeValue;
    autocomplete: string;
  }
  interface PageAccountBio {
    id: string;
    label: string;
    value: string;
  }
  interface PageAccountPhoto {
    formats: string;
    maxSize: string;
  }
  interface PageAccountPasswordField {
    id: string;
    label: string;
    autocomplete: string;
  }
  interface PageBilling {
    heading: string;
    sub: string;
    plan: DreamBoard.PageBillingPlan;
    payment: DreamBoard.PageBillingPayment;
    invoices: DreamBoard.PageBillingInvoice[];
  }
  interface PageBillingPlan {
    name: string;
    price: number;
    period: string;
    renews: string;
    seats: string;
  }
  interface PageBillingPayment {
    brand: string;
    last4: string;
    expiry: string;
    holder: string;
  }
  interface PageBillingInvoice {
    id: string;
    date: string;
    amount: number;
    status: DreamBoard.StatusValue;
  }
  interface PageSignout {
    heading: string;
    body: string;
  }
  interface PageAnalytic {
    heading: string;
    sub: string;
    stats: DreamBoard.PageAnalyticStat[];
    traffic: DreamBoard.RevenueChart;
    channels: DreamBoard.OrdersChart;
    topPages: DreamBoard.PageAnalyticTopPage[];
    devices: DreamBoard.PageAnalyticDevice[];
    countries: DreamBoard.PageAnalyticCountrie[];
  }
  interface PageAnalyticStat {
    id: string;
    label: string;
    value: number;
    format: string;
    delta: string;
    deltaDir: string;
    deltaLabel: string;
    icon: string;
    spark: number[];
  }
  interface PageAnalyticTopPage {
    path: string;
    views: number;
    uniques: number;
    bounce: string;
  }
  interface PageAnalyticDevice {
    name: string;
    icon: string;
    share: number;
  }
  interface PageAnalyticCountrie {
    name: string;
    code: string;
    lon: number;
    lat: number;
    users: number;
    share: number;
  }
  interface PageReport {
    heading: string;
    sub: string;
    stats: DreamBoard.PageReportStat[];
    items: DreamBoard.PageReportItem[];
  }
  interface PageReportStat {
    label: string;
    value: number;
    icon: string;
  }
  interface PageReportItem {
    id: string;
    name: string;
    range: string;
    created: string;
    format: string;
    size: string;
    status: DreamBoard.StatusValue;
  }
  interface PageRealtime {
    heading: string;
    sub: string;
    activeNow: number;
    eventsNow: number;
    perMinute: number[];
    eventsPerMinute: number[];
    funnel: DreamBoard.PageRealtimeFunnel[];
    countries: DreamBoard.PageAnalyticCountrie[];
    agents: DreamBoard.PageRealtimeAgent[];
    topActivePages: DreamBoard.PageRealtimeTopActivePage[];
    feed: DreamBoard.PageRealtimeFeed[];
    feedPool: DreamBoard.PageRealtimeFeedPool[];
  }
  interface PageRealtimeFunnel {
    key: string;
    label: string;
    icon: string;
    value: number;
  }
  interface PageRealtimeAgent {
    name: string;
    icon: string;
    share: number;
    users: number;
  }
  interface PageRealtimeTopActivePage {
    path: string;
    users: number;
  }
  interface PageRealtimeFeed {
    actor: string;
    action: string;
    target: string;
    icon: string;
  }
  interface PageRealtimeFeedPool {
    actor: string;
    action: string;
    target: string;
    icon: string;
  }
  interface PageReportNew {
    heading: string;
    sub: string;
    fields: DreamBoard.PageReportNewField;
  }
  interface PageReportNewField {
    nameLabel: string;
    namePlaceholder: string;
    typeLabel: string;
    types: string[];
    rangeLabel: string;
    ranges: string[];
    sectionsLabel: string;
    sections: string[];
    formatLabel: string;
    formats: string[];
    scheduleLabel: string;
    schedules: string[];
    emailLabel: string;
    emailPlaceholder: string;
    emailHint: string;
  }
  interface PageOrder {
    heading: string;
    sub: string;
    stats: DreamBoard.PageOrderStat[];
    filters: DreamBoard.PageOrderFilter[];
    items: DreamBoard.PageOrderItem[];
    detail: DreamBoard.PageOrderDetail;
  }
  interface PageOrderStat {
    label: string;
    value: number;
    icon: string;
    format?: string;
  }
  interface PageOrderFilter {
    key: string;
    label: string;
  }
  interface PageOrderItem {
    id: string;
    customer: string;
    email: string;
    address: string;
    payment: string;
    qty: number;
    product: string;
    date: string;
    amount: number;
    status: DreamBoard.StatusValue;
  }
  interface PageOrderDetail {
    timelineTitle: string;
    timeline: DreamBoard.PageOrderDetailTimeline[];
  }
  interface PageOrderDetailTimeline {
    icon: string;
    label: string;
    time: string;
  }
  interface PageProduct {
    heading: string;
    sub: string;
    stats: DreamBoard.PageProductStat[];
    items: DreamBoard.PageProductItem[];
    detail: DreamBoard.PageProductDetail;
  }
  interface PageProductStat {
    label: string;
    value: number;
    icon: string;
  }
  interface PageProductItem {
    id: string;
    name: string;
    category: string;
    price: number;
    stock: number;
    rating: number;
    status: DreamBoard.StatusValue;
  }
  interface PageProductDetail {
    blurb: string;
    statsTitle: string;
    stats: DreamBoard.PageProductDetailStat[];
  }
  interface PageProductDetailStat {
    label: string;
    value: number;
    icon: string;
    format?: string;
  }
  interface PageCustomer {
    heading: string;
    sub: string;
    stats: DreamBoard.PageCustomerStat[];
    items: DreamBoard.PageCustomerItem[];
  }
  interface PageCustomerStat {
    label: string;
    value: number;
    icon: string;
    format?: string;
  }
  interface PageCustomerItem {
    id: string;
    name: string;
    email: string;
    country: string;
    orders: number;
    spent: number;
    status: DreamBoard.StatusValue;
    joined: string;
  }
  interface PageNotificationsPage {
    heading: string;
    sub: string;
  }
  interface PageAuditLog {
    heading: string;
    sub: string;
    types: DreamBoard.PageAuditLogType[];
    events: DreamBoard.PageAuditLogEvent[];
  }
  interface PageAuditLogType {
    key: string;
    label: string;
    icon: string;
    variant: DreamBoard.VariantValue;
  }
  interface PageAuditLogEvent {
    id: string;
    ts: string;
    type: DreamBoard.TypeValue | string;
    icon: string;
    actor: string;
    action: string;
    target: string;
    ip: string;
    status: DreamBoard.StatusValue;
  }
  interface PageTask {
    heading: string;
    sub: string;
    assignees: string[];
    tagOptions: DreamBoard.PageTaskTagOption[];
    columns: DreamBoard.PageTaskColumn[];
  }
  interface PageTaskTagOption {
    tag: string;
    variant: DreamBoard.VariantValue;
  }
  interface PageTaskColumn {
    id: string;
    color: string;
    title: string;
    items: DreamBoard.PageTaskColumnItem[];
  }
  interface PageTaskColumnItem {
    id: string;
    title: string;
    tag: string;
    tagVariant: string;
    assignee: string;
    due: string;
  }
  interface PageCalendar {
    heading: string;
    sub: string;
    initialMonth: string;
    weekdays: string[];
    variants: DreamBoard.PageOrderFilter[];
    events: DreamBoard.PageCalendarEvent[];
  }
  interface PageCalendarEvent {
    id: string;
    date: string;
    title: string;
    variant: DreamBoard.VariantValue;
  }
  interface PageAuth {
    signin: DreamBoard.PageAuthSignin;
    signup: DreamBoard.PageNotificationsPage;
    forgot: DreamBoard.PageNotificationsPage;
    verify: DreamBoard.PageNotificationsPage;
    reset: DreamBoard.PageNotificationsPage;
    otp: DreamBoard.PageNotificationsPage;
    notFound: DreamBoard.PageNotificationsPage;
    serverError: DreamBoard.PageNotificationsPage;
    maintenance: DreamBoard.PageNotificationsPage;
    comingSoon: DreamBoard.PageNotificationsPage;
    lockScreen: DreamBoard.PageNotificationsPage;
  }
  interface PageAuthSignin {
    heading: string;
    sub: string;
    providers: DreamBoard.PageAuthSigninProvider[];
  }
  interface PageAuthSigninProvider {
    name: string;
    icon: string;
  }
  interface PageInbox {
    heading: string;
    sub: string;
    boxes: DreamBoard.PageInboxBoxe[];
    messages: DreamBoard.PageInboxMessage[];
  }
  interface PageInboxBoxe {
    key: string;
    label: string;
    icon: string;
  }
  interface PageInboxMessage {
    id: string;
    from: string;
    email: string;
    subject: string;
    preview: string;
    time: string;
    unread: boolean;
    starred: boolean;
    body: string;
  }
  interface PageFile {
    heading: string;
    sub: string;
    quota: DreamBoard.PageFileQuota;
    folders: DreamBoard.PageFileFolder[];
    items: DreamBoard.PageFileItem[];
  }
  interface PageFileQuota {
    used: number;
    limit: number;
    unit: string;
  }
  interface PageFileFolder {
    id: string;
    name: string;
    parent: null | string;
    files: number;
    size: string;
  }
  interface PageFileItem {
    id: string;
    name: string;
    icon: string;
    size: string;
    modified: string;
    owner: string;
    folder: string | null;
  }
  interface PageInvoice {
    heading: string;
    sub: string;
    inv: DreamBoard.PageInvoiceInv;
  }
  interface PageInvoiceInv {
    number: string;
    status: DreamBoard.StatusValue;
    issued: string;
    due: string;
    from: DreamBoard.PageInvoiceInvFrom;
    to: DreamBoard.PageInvoiceInvFrom;
    items: DreamBoard.PageInvoiceInvItem[];
    taxRate: number;
    note: string;
  }
  interface PageInvoiceInvFrom {
    name: string;
    lines: string[];
  }
  interface PageInvoiceInvItem {
    desc: string;
    qty: number;
    price: number;
  }
  interface PagePricing {
    heading: string;
    sub: string;
    cycle: DreamBoard.PagePricingCycle;
    tiers: DreamBoard.PagePricingTier[];
  }
  interface PagePricingCycle {
    monthly: string;
    annual: string;
    save: string;
  }
  interface PagePricingTier {
    name: string;
    monthly: number;
    annual: number;
    desc: string;
    features: string[];
    cta: string;
    popular: boolean;
  }
  interface PageUser {
    heading: string;
    sub: string;
    activity: DreamBoard.PageUserActivity[];
  }
  interface PageUserActivity {
    title: string;
    body: string;
    time: string;
    variant: DreamBoard.VariantValue;
  }
  interface PageLanding {
    heading: string;
    sub: string;
    ctaPrimary: string;
    ctaSecondary: string;
    featuresTitle: string;
    featuresSub: string;
    features: DreamBoard.PageLandingFeature[];
    bannerTitle: string;
    bannerSub: string;
    bannerCta: string;
    footNote: string;
  }
  interface PageLandingFeature {
    icon: string;
    title: string;
    body: string;
  }
  interface PageLanding2 {
    badge: string;
    heading: string;
    sub: string;
    ctaPrimary: string;
    ctaSecondary: string;
    accentsLabel: string;
    stats: DreamBoard.PageLanding2Stat[];
    featuresTitle: string;
    featuresSub: string;
    bento: DreamBoard.PageLanding2Bento[];
    quote: DreamBoard.PageLanding2Quote;
    bannerTitle: string;
    bannerSub: string;
    bannerCta: string;
    footNote: string;
  }
  interface PageLanding2Stat {
    label: string;
    value: string;
  }
  interface PageLanding2Bento {
    icon: string;
    title: string;
    body: string;
    size: string;
  }
  interface PageLanding2Quote {
    text: string;
    name: string;
    role: string;
  }
  interface PageLanding3 {
    badge: string;
    headingA: string;
    headingB: string;
    sub: string;
    ctaPrimary: string;
    ctaSecondary: string;
    logosLabel: string;
    logos: string[];
    stepsTitle: string;
    stepsSub: string;
    steps: DreamBoard.PageLanding3Step[];
    quotesTitle: string;
    quotes: DreamBoard.PageLanding2Quote[];
    bannerTitle: string;
    bannerSub: string;
    bannerCta: string;
    footNote: string;
  }
  interface PageLanding3Step {
    title: string;
    body: string;
  }
  interface PageLanding4 {
    badge: string;
    heading: string;
    sub: string;
    ctaPrimary: string;
    ctaSecondary: string;
    accentsLabel: string;
    darkToggle: string;
    heroChips: DreamBoard.PageLanding4HeroChip[];
    stats: DreamBoard.PageLanding2Stat[];
    boxTitle: string;
    boxSub: string;
    box: string[];
    featuresTitle: string;
    featuresSub: string;
    bento: DreamBoard.PageLanding4Bento[];
    teaserTitle: string;
    teaserSub: string;
    teaserPrice: string;
    teaserPoints: string[];
    teaserCta: string;
    quote: DreamBoard.PageLanding2Quote;
    bannerTitle: string;
    bannerSub: string;
    bannerCta: string;
    reassure: string[];
    footNote: string;
  }
  interface PageLanding4HeroChip {
    icon: string;
    label: string;
  }
  interface PageLanding4Bento {
    icon: string;
    title: string;
    body: string;
    size: string;
  }
  interface PageLanding5 {
    badge: string;
    heading: string;
    sub: string;
    ctaPrimary: string;
    ctaSecondary: string;
    accentsLabel: string;
    logosLabel: string;
    logos: string[];
    rowsTitle: string;
    rowsSub: string;
    rows: DreamBoard.PageLanding5Row[];
    vsTitle: string;
    vsSub: string;
    vsDiyTitle: string;
    vsKitTitle: string;
    vsRows: DreamBoard.PageLanding5VsRow[];
    vsVerdict: string;
    quote: DreamBoard.PageLanding2Quote;
    bannerTitle: string;
    bannerSub: string;
    bannerCta: string;
    reassure: string[];
    footNote: string;
  }
  interface PageLanding5Row {
    icon: string;
    title: string;
    body: string;
    points: string[];
    visual: string;
  }
  interface PageLanding5VsRow {
    label: string;
    diy: string;
    kit: string;
  }
  interface PageLanding6 {
    badge: string;
    headingA: string;
    headingB: string;
    sub: string;
    ctaPrimary: string;
    ctaSecondary: string;
    logosLabel: string;
    logos: string[];
    accentTitle: string;
    accentSub: string;
    accentsLabel: string;
    previewCardTitle: string;
    previewCardValue: string;
    previewCardDelta: string;
    featuresTitle: string;
    featuresSub: string;
    bento: DreamBoard.PageLanding2Bento[];
    stepsTitle: string;
    stepsSub: string;
    steps: DreamBoard.PageLanding3Step[];
    quotesTitle: string;
    quotes: DreamBoard.PageLanding2Quote[];
    bannerTitle: string;
    bannerSub: string;
    bannerCta: string;
    reassure: string[];
    footNote: string;
  }
  interface PageChart {
    heading: string;
    sub: string;
    cards: DreamBoard.PageChartCard[];
  }
  interface PageChartCard {
    key: string;
    type: DreamBoard.TypeValue;
    title: string;
    sub: string;
    labels: string[];
    series: DreamBoard.RevenueChartSeries[] | number[];
    horizontal?: boolean;
    live?: boolean;
  }
  interface PageChartsAdvanced {
    heading: string;
    sub: string;
    cards: DreamBoard.PageChartsAdvancedCard[];
  }
  interface PageChartsAdvancedCard {
    key: string;
    type: DreamBoard.TypeValue;
    wide?: boolean;
    title: string;
    sub: string;
    labels?: string[];
    series?: DreamBoard.PageChartsAdvancedCardSeries[] | DreamBoard.RevenueChartSeries[] | DreamBoard.PageChartsAdvancedCardSeries2[] | DreamBoard.PageChartsAdvancedCardSeries3[] | number[] | DreamBoard.PageChartsAdvancedCardSeries4[];
    mapLimit?: number;
    countries?: DreamBoard.PageAnalyticCountrie[];
  }
  interface PageChartsAdvancedCardSeries {
    name: string;
    data: DreamBoard.PageChartsAdvancedCardSeriesData[];
  }
  interface PageChartsAdvancedCardSeriesData {
    x: string;
    y: number;
  }
  interface PageChartsAdvancedCardSeries2 {
    data: DreamBoard.PageChartsAdvancedCardSeriesData2[];
  }
  interface PageChartsAdvancedCardSeriesData2 {
    x: string;
    y: number[];
  }
  interface PageChartsAdvancedCardSeries3 {
    data: DreamBoard.PageChartsAdvancedCardSeriesData[];
  }
  interface PageChartsAdvancedCardSeries4 {
    name: string;
    data: number[][];
  }
  interface PageFaq {
    heading: string;
    sub: string;
    groups: DreamBoard.PageFaqGroup[];
  }
  interface PageFaqGroup {
    label: string;
    items: DreamBoard.PageFaqGroupItem[];
  }
  interface PageFaqGroupItem {
    q: string;
    a: string;
  }
  interface PageHelp {
    heading: string;
    sub: string;
    searchPlaceholder: string;
    docsUrl: string;
    topics: DreamBoard.PageHelpTopic[];
    articles: DreamBoard.PageHelpArticle[];
    supportTitle: string;
    supportSub: string;
    support: DreamBoard.PageHelpSupport[];
    noResults: string;
  }
  interface PageHelpTopic {
    icon: string;
    label: string;
    desc: string;
    articles: number;
  }
  interface PageHelpArticle {
    icon: string;
    topic: string;
    title: string;
    excerpt: string;
    minutes: number;
  }
  interface PageHelpSupport {
    icon: string;
    label: string;
    desc: string;
    href: string;
  }
  interface PageForm {
    heading: string;
    sub: string;
    stackedFields: DreamBoard.PageFormStackedField[];
    gridFields: DreamBoard.PageFormGridField[];
    states: DreamBoard.PageFormState[];
    wizardSteps: DreamBoard.PageFormWizardStep[];
    wizardFields: (DreamBoard.PageFormWizardField[] | DreamBoard.PageFormGridField[] | unknown[])[];
  }
  interface PageFormStackedField {
    id: string;
    label: string;
    type: DreamBoard.TypeValue;
    autocomplete?: string;
    required: boolean;
    value: string;
  }
  interface PageFormGridField {
    id: string;
    label: string;
    type: DreamBoard.TypeValue;
    autocomplete?: string;
    required: boolean;
    value: string;
  }
  interface PageFormState {
    id: string;
    label: string;
    value: string;
    state: string;
    hint: string;
  }
  interface PageFormWizardStep {
    title: string;
    desc: string;
  }
  interface PageFormWizardField {
    id: string;
    label: string;
    type: DreamBoard.TypeValue;
    autocomplete: string;
    required: boolean;
    value: string;
  }
  interface PageOnboarding {
    heading: string;
    sub: string;
    steps: DreamBoard.PageFormWizardStep[];
    roles: DreamBoard.PageOnboardingRole[];
  }
  interface PageOnboardingRole {
    key: string;
    label: string;
    icon: string;
  }
  interface PageAiChat {
    heading: string;
    sub: string;
    models: DreamBoard.PageAiChatModel[];
    conversations: DreamBoard.PageAiChatConversation[];
    threads: DreamBoard.PageAiChatThread;
    replies: string[];
    suggestions: string[];
  }
  interface PageAiChatModel {
    name: string;
    desc: string;
  }
  interface PageAiChatConversation {
    id: string;
    title: string;
    model: string;
    updated: string;
    preview: string;
    pinned: boolean;
    unread: boolean;
  }
  interface PageAiChatThread {
    c1: DreamBoard.PageAiChatThreadC1[];
    c2: DreamBoard.PageAiChatThreadC1[];
  }
  interface PageAiChatThreadC1 {
    role: string;
    text: string;
    time: string;
    tokens: number;
  }
  interface PageAiAgent {
    heading: string;
    sub: string;
    stats: DreamBoard.PageAiAgentStat[];
    items: DreamBoard.PageAiAgentItem[];
  }
  interface PageAiAgentStat {
    label: string;
    value: number;
    format: string;
    icon: string;
  }
  interface PageAiAgentItem {
    id: string;
    name: string;
    desc: string;
    icon: string;
    status: DreamBoard.StatusValue;
    runs: number;
    success: number;
    lastRun: string;
    schedule: string;
  }
  interface PageAiPrompt {
    heading: string;
    sub: string;
    categories: string[];
    items: DreamBoard.PageAiPromptItem[];
  }
  interface PageAiPromptItem {
    id: string;
    title: string;
    desc: string;
    category: string;
    uses: number;
    prompt: string;
  }
  interface PageAiModel {
    heading: string;
    sub: string;
    stats: DreamBoard.PageAiModelStat[];
    items: DreamBoard.PageAiModelItem[];
  }
  interface PageAiModelStat {
    label: string;
    value: number;
    format: string;
    icon: string;
  }
  interface PageAiModelItem {
    name: string;
    provider: string;
    context: string;
    input: number;
    output: number;
    latency: string;
    quality: number;
    status: DreamBoard.StatusValue;
    default: boolean;
  }
  interface PageAiUsage {
    heading: string;
    sub: string;
    stats: DreamBoard.PageAiUsageStat[];
    chart: DreamBoard.PageAiUsageChart;
    perModel: DreamBoard.PageAiUsagePerModel[];
    quota: DreamBoard.PageAiUsageQuota;
  }
  interface PageAiUsageStat {
    label: string;
    value: number;
    format: string;
    icon: string;
  }
  interface PageAiUsageChart {
    labels: string[];
    series: number[];
  }
  interface PageAiUsagePerModel {
    model: string;
    tokens: number;
    requests: number;
    cost: number;
    share: number;
  }
  interface PageAiUsageQuota {
    plan: string;
    used: number;
    limit: number;
    resetsIn: number;
  }
  interface PageAiKey {
    heading: string;
    sub: string;
    items: DreamBoard.PageAiKeyItem[];
    scopes: string[];
  }
  interface PageAiKeyItem {
    id: string;
    name: string;
    prefix: string;
    created: string;
    lastUsed: string;
    scopes: string[];
    status: DreamBoard.StatusValue;
  }
  interface PageAiMember {
    heading: string;
    sub: string;
    stats: DreamBoard.PageAiMemberStat[];
    roles: string[];
    items: DreamBoard.PageAiMemberItem[];
  }
  interface PageAiMemberStat {
    label: string;
    value: number;
    format: string;
    icon: string;
  }
  interface PageAiMemberItem {
    name: string;
    email: string;
    role: string;
    status: DreamBoard.StatusValue;
    lastActive: string;
  }
  interface Ui {
    tabs: DreamBoard.UiTab[];
    alerts: DreamBoard.UiAlert[];
    badges: DreamBoard.UiBadge[];
    accents: DreamBoard.UiAccent[];
    tagSeed: string[];
    tooltipDemos: DreamBoard.UiTooltipDemo[];
    toastDemos: DreamBoard.UiAlert[];
    plans: string[];
    explorer: DreamBoard.UiExplorer[];
    explorerCats: string[];
    explorerFixtures: DreamBoard.UiExplorerFixture;
  }
  interface UiTab {
    id: string;
    label: string;
    heading: string;
    body: string;
  }
  interface UiAlert {
    variant: DreamBoard.VariantValue;
    title: string;
    body: string;
  }
  interface UiBadge {
    label: string;
    variant: DreamBoard.VariantValue;
  }
  interface UiAccent {
    key: string;
    label: string;
    hex: string;
  }
  interface UiTooltipDemo {
    key: string;
    label: string;
    tip: string;
    pos: DreamBoard.PosValue;
  }
  interface UiExplorer {
    id: string;
    cat: string;
    label: string;
    file: string;
    snippet: string;
    binds: string;
  }
  interface UiExplorerFixture {
    stat: DreamBoard.Stat2;
    mini: DreamBoard.PageAiMemberStat2;
    chart: DreamBoard.PageChartCard2;
    countries: DreamBoard.PageAnalyticCountrie[];
    timeline: DreamBoard.PageUserActivity[];
    crumbs: DreamBoard.UiExplorerFixtureCrumb[];
    cols: DreamBoard.UiExplorerFixtureCol[];
    rows: DreamBoard.UiExplorerFixtureRow[];
  }
  interface Stat2 {
    id: string;
    label: string;
    value: number;
    format: string;
    delta: string;
    deltaDir: string;
    deltaLabel: string;
    icon: string;
    spark: number[];
  }
  interface PageAiMemberStat2 {
    label: string;
    value: number;
    format: string;
    icon: string;
  }
  interface PageChartCard2 {
    key: string;
    type: DreamBoard.TypeValue;
    title: string;
    sub: string;
    labels: string[];
    series: DreamBoard.RevenueChartSeries[];
  }
  interface UiExplorerFixtureCrumb {
    label: string;
    href?: string;
  }
  interface UiExplorerFixtureCol {
    key: string;
    label: string;
    sort?: boolean;
  }
  interface UiExplorerFixtureRow {
    id: string;
    name: string;
    role: string;
    status: DreamBoard.StatusValue;
  }
  interface Ai {
    quota: DreamBoard.AiQuota;
  }
  interface AiQuota {
    plan: string;
    used: number;
    limit: number;
    usedPct: number;
    resetsIn: number;
  }
  interface I18n {
    defaultLocale: string;
    locales: string[];
    flags: Record<string, string>;
    dict: Record<string, Record<string, string>>;
  }
}

interface Window {
  mockData: DreamBoard.MockData;
  i18n: DreamBoard.I18n;
}
