/**
 * Semantic icon key → Phosphor icon name (duotone weight).
 * Consumed by the icon codegen, which vendors the referenced SVGs from
 * @phosphor-icons/core into a runtime registry (window.PHOSPHOR_ICONS
 * in the HTML edition, src/icons.js in the React edition).
 * mockData and templates only ever reference the semantic keys below.
 */
module.exports = {
  dashboard: "squares-four",
  chart: "chart-line-up",
  cart: "shopping-cart",
  columns: "columns",
  users: "users",
  user: "user",
  revenue: "currency-circle-dollar",
  trend: "trend-up",
  grid: "grid-four",
  calendar: "calendar-blank",
  settings: "gear-six",
  bell: "bell",
  search: "magnifying-glass",
  sun: "sun",
  moon: "moon",
  menu: "list",
  close: "x",
  chevronDown: "caret-down",
  chevronLeft: "caret-left",
  chevronRight: "caret-right",
  star: "star",
  shield: "shield-check",
  refund: "arrow-counter-clockwise",
  alert: "warning",
  info: "info",
  check: "check-circle",
  checkPlain: "check",
  heart: "heart",
  card: "credit-card",
  logout: "sign-out",
  plus: "plus",
  dots: "dots-three",
  dotsV: "dots-three-vertical",
  arrowUp: "arrow-up",
  arrowDown: "arrow-down",
  mail: "envelope-simple",
  phone: "phone",
  globe: "globe",
  // Browser marks — only Chrome ships a brand icon in Phosphor; the rest
  // are recognizable metaphors (Safari compass, Firefox flame, Edge swirl).
  chrome: "google-chrome-logo",
  safari: "compass",
  firefox: "fire",
  edge: "hurricane",
  pin: "map-pin",
  pencil: "pencil-simple",
  download: "download-simple",
  upload: "upload-simple",
  trash: "trash",
  eye: "eye",
  clock: "clock",
  file: "file-text",
  desktop: "desktop",
  mobile: "device-mobile",
  tablet: "device-tablet",
  pulse: "pulse",
  package: "package",
  tag: "tag",
  wallet: "wallet",
  google: "google-logo",
  github: "github-logo",
  sort: "arrows-down-up",
  palette: "palette",
  sparkle: "sparkle",
  robot: "robot",
  wand: "magic-wand",
  brain: "brain",
  gauge: "gauge",
  key: "key",
  send: "paper-plane-tilt",
  copy: "copy",
  refresh: "arrows-clockwise",
  paperclip: "paperclip",
  mic: "microphone",
  cpu: "cpu",
  bolt: "lightning",
  userPlus: "user-plus",
  translate: "translate",
  kanban: "kanban",
  funnel: "funnel",
  checks: "checks",
  tray: "tray",
  sidebar: "sidebar-simple",
  rows: "rows",
  receipt: "receipt",
  lockKey: "lock-key",
  envelopeOpen: "envelope-open",
  reply: "arrow-bend-up-left",
  forward: "arrow-bend-up-right",
  archive: "archive",
  drag: "dots-six-vertical",
  folder: "folder",
  files: "files",
  question: "question",
  clipboard: "clipboard-text",
  printer: "printer",
  wrench: "wrench",
  invoice: "invoice",
  pen: "pen-nib",
  filePdf: "file-pdf",
  fileImg: "file-image",
  fileVid: "file-video",
  fileZip: "file-zip",
  fileDoc: "file-doc",
  fileXls: "file-xls",
  fileAudio: "file-audio",
};

/**
 * Extra weights vendored per key (every key always gets `duotone`).
 * Add a weight here only when a template calls $icon(key, cls, weight).
 */
module.exports.WEIGHTS = {
  // regular — icons inside buttons
  dotsV: ["regular"],
  bell: ["regular"],
  calendar: ["regular"],
  chevronDown: ["regular"],
  chevronLeft: ["regular"],
  columns: ["regular"],
  chevronRight: ["regular"],
  close: ["regular"],
  download: ["regular"],
  menu: ["regular"],
  moon: ["regular"],
  palette: ["regular"],
  pencil: ["regular"],
  plus: ["regular"],
  search: ["regular"],
  sun: ["regular"],
  trash: ["regular"],
  copy: ["regular"],
  mic: ["regular"],
  paperclip: ["regular"],
  refresh: ["regular"],
  send: ["regular"],
  userPlus: ["regular"],
  translate: ["regular"],
  rows: ["regular"],
  sidebar: ["regular"],
  checks: ["regular"],
  funnel: ["regular"],
  printer: ["regular"],
  lockKey: ["regular"],
  // bold — plain checkmarks (checkbox, select option, accent menu)
  checkPlain: ["regular", "bold"],
  // fill — rating star + brand logos + footer heart
  heart: ["fill"],
  star: ["fill"],
  google: ["fill"],
  github: ["fill"],
};
